### Get all images
GET http://localhost:3000/api/images

### Get one image
GET http://localhost:3000/api/images/69ab49023fc4a574c4de9d14

### Rename image successfully
PATCH http://localhost:3000/api/images/69ab49023fc4a574c4de9d14
Content-Type: application/json

{
  "name": "Cool Dog Photo"
}

### Rename image - bad request (missing name)
PATCH http://localhost:3000/api/images/69ab49023fc4a574c4de9d14
Content-Type: application/json

{}

### Rename image - too long
PATCH http://localhost:3000/api/images/69ab49023fc4a574c4de9d14
Content-Type: application/json

{
  "name": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}

### Rename image - image does not exist
PATCH http://localhost:3000/api/images/123456789012345678901234
Content-Type: application/json

{
  "name": "Does not exist"
}